In [2]:
#Basics of Networkx

import networkx as nx

G = nx.Graph()
G.add_node(1)
G.add_nodes_from(["u","v"])

G.add_edge(1,2)
G.add_edge("u","v")
G.add_edges_from([(1,3),(1,4),(1,5),(1,6)])
G.add_edge("u","w")

G.remove_nodes_from([4,5])
G.remove_edge(1,3)

G.number_of_nodes()

7

In [3]:
#Graph Visualization
import matplotlib.pyplot as plt
%matplotlib widget
G= nx.karate_club_graph()
nx.draw(G, with_labels=True, node_color="lightblue", edge_color="grey")
plt.show()
print(G.degree()) # Dictionary of Ties or friendships of that particular node
G.degree(2) # or G.degree[2]

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

[(0, 16), (1, 9), (2, 10), (3, 6), (4, 3), (5, 4), (6, 4), (7, 4), (8, 5), (9, 2), (10, 3), (11, 1), (12, 2), (13, 5), (14, 2), (15, 2), (16, 2), (17, 2), (18, 2), (19, 3), (20, 2), (21, 2), (22, 2), (23, 5), (24, 3), (25, 3), (26, 2), (27, 4), (28, 3), (29, 4), (30, 4), (31, 6), (32, 12), (33, 17)]


10

In [4]:
# Random Graphs
from scipy.stats import bernoulli
%matplotlib widget
bernoulli.rvs(p=0.2)

def er_graph(N,p):  
    '''Generate an ER graph'''
    #Specify number of nodes
    #Probability of an edge between a pair of nodes
    #Loop over all pairs and add en edge with probability p
    G = nx.Graph()
    G.add_nodes_from(range(N))
    for node1 in G.nodes():
        for node2 in G.nodes():
            if node1 < node2 and bernoulli.rvs(p=p): # f it returns 1 i.e True, condition to consider a pair only once
                G.add_edge(node1,node2) 
    return G
nx.draw(er_graph(50,0.1), node_size=20)

#we can also use nx.erdos_renyi_graph()


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [5]:
#Plotting the Degree distribution
%matplotlib widget
def plot_degree_distribution(G):
    degree_sequence=[d for n,d in G.degree()]
    plt.hist(degree_sequence, histtype= "step")
    plt.xlabel("Degree $k$")
    plt.ylabel("$P(k)$")
    plt.title("Degree distribution")
G1 = er_graph(500,0.08)
plot_degree_distribution(G1)
G2 = er_graph(500,0.08)
plot_degree_distribution(G2)
G3 = er_graph(500,0.08)
plot_degree_distribution(G3)

#getting a more clear idea

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [6]:
# Descriptive Statistics of Empirical Social Networks
import numpy as np
%matplotlib widget
A1 = np.loadtxt("adj_allVillageRelationships_vilno_1.csv" , delimiter= ",")
A2 = np.loadtxt("adj_allVillageRelationships_vilno_2.csv" , delimiter= ",")

G1 = nx.to_networkx_graph(A1)
G2 = nx.to_networkx_graph(A2)

def basic_net_stats(G):
    degree_sequence = [d for n,d in G.degree()]
    print("Number of nodes: %d" %G.number_of_nodes())
    print("Number of edges: %d" %G.number_of_edges())
    print("Average degree: %.2f" % np.mean(degree_sequence))
basic_net_stats(G1)
basic_net_stats(G2)

plot_degree_distribution(G1)
plot_degree_distribution(G2)
# Inference: More people having fewer connections , Reference: ER graph

Number of nodes: 843
Number of edges: 3405
Average degree: 8.08
Number of nodes: 877
Number of edges: 3063
Average degree: 6.99


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

[[0. 1. 1. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 1.]
 [0. 0. 0. ... 1. 0. 1.]
 [0. 0. 0. ... 1. 1. 0.]]


In [8]:
# Finding the Largest Connected Component
%matplotlib widget

Gcc1= sorted(nx.connected_components(G1), key=len, reverse=True)
Gcc2= sorted(nx.connected_components(G2), key=len, reverse=True)
G1max = G1.subgraph(Gcc1[0])
G2max = G2.subgraph(Gcc2[0])

#percentage of nodes in largest component

p = (len(G1max)/G1.number_of_nodes())*100

plt.figure()
nx.draw(G1max, node_color="red" , edge_color="gray", node_size=20)
plt.figure()
nx.draw(G2max, node_color="blue" , edge_color="gray", node_size=20)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …